sudo: false

language: go

git:
  depth: 1

install: go get -v github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: ${GH_TOKEN}
  on:
    branch: master
  local_dir: public
  repo: Huramkin/Huramkin.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot